/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.AccountingClient.Client.OpenAPIDateConverter;

namespace Merge.AccountingClient.Model
{
    /// <summary>
    /// * &#x60;ASSET&#x60; - ASSET * &#x60;EQUITY&#x60; - EQUITY * &#x60;EXPENSE&#x60; - EXPENSE * &#x60;LIABILITY&#x60; - LIABILITY * &#x60;REVENUE&#x60; - REVENUE
    /// </summary>
    /// <value>* &#x60;ASSET&#x60; - ASSET * &#x60;EQUITY&#x60; - EQUITY * &#x60;EXPENSE&#x60; - EXPENSE * &#x60;LIABILITY&#x60; - LIABILITY * &#x60;REVENUE&#x60; - REVENUE</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ClassificationEnum
    {
        /// <summary>
        /// Enum ASSET for value: ASSET
        /// </summary>
        [EnumMember(Value = "ASSET")]
        ASSET = 1,

        /// <summary>
        /// Enum EQUITY for value: EQUITY
        /// </summary>
        [EnumMember(Value = "EQUITY")]
        EQUITY = 2,

        /// <summary>
        /// Enum EXPENSE for value: EXPENSE
        /// </summary>
        [EnumMember(Value = "EXPENSE")]
        EXPENSE = 3,

        /// <summary>
        /// Enum LIABILITY for value: LIABILITY
        /// </summary>
        [EnumMember(Value = "LIABILITY")]
        LIABILITY = 4,

        /// <summary>
        /// Enum REVENUE for value: REVENUE
        /// </summary>
        [EnumMember(Value = "REVENUE")]
        REVENUE = 5

    }

}
