/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.AccountingClient.Client.OpenAPIDateConverter;

namespace Merge.AccountingClient.Model
{
    /// <summary>
    /// Defines StateEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StateEnum
    {
        /// <summary>
        /// Enum AL for value: AL
        /// </summary>
        [EnumMember(Value = "AL")]
        AL = 1,

        /// <summary>
        /// Enum AK for value: AK
        /// </summary>
        [EnumMember(Value = "AK")]
        AK = 2,

        /// <summary>
        /// Enum AS for value: AS
        /// </summary>
        [EnumMember(Value = "AS")]
        AS = 3,

        /// <summary>
        /// Enum AZ for value: AZ
        /// </summary>
        [EnumMember(Value = "AZ")]
        AZ = 4,

        /// <summary>
        /// Enum AR for value: AR
        /// </summary>
        [EnumMember(Value = "AR")]
        AR = 5,

        /// <summary>
        /// Enum AA for value: AA
        /// </summary>
        [EnumMember(Value = "AA")]
        AA = 6,

        /// <summary>
        /// Enum AE for value: AE
        /// </summary>
        [EnumMember(Value = "AE")]
        AE = 7,

        /// <summary>
        /// Enum AP for value: AP
        /// </summary>
        [EnumMember(Value = "AP")]
        AP = 8,

        /// <summary>
        /// Enum CA for value: CA
        /// </summary>
        [EnumMember(Value = "CA")]
        CA = 9,

        /// <summary>
        /// Enum CO for value: CO
        /// </summary>
        [EnumMember(Value = "CO")]
        CO = 10,

        /// <summary>
        /// Enum CT for value: CT
        /// </summary>
        [EnumMember(Value = "CT")]
        CT = 11,

        /// <summary>
        /// Enum DE for value: DE
        /// </summary>
        [EnumMember(Value = "DE")]
        DE = 12,

        /// <summary>
        /// Enum DC for value: DC
        /// </summary>
        [EnumMember(Value = "DC")]
        DC = 13,

        /// <summary>
        /// Enum FL for value: FL
        /// </summary>
        [EnumMember(Value = "FL")]
        FL = 14,

        /// <summary>
        /// Enum GA for value: GA
        /// </summary>
        [EnumMember(Value = "GA")]
        GA = 15,

        /// <summary>
        /// Enum GU for value: GU
        /// </summary>
        [EnumMember(Value = "GU")]
        GU = 16,

        /// <summary>
        /// Enum HI for value: HI
        /// </summary>
        [EnumMember(Value = "HI")]
        HI = 17,

        /// <summary>
        /// Enum ID for value: ID
        /// </summary>
        [EnumMember(Value = "ID")]
        ID = 18,

        /// <summary>
        /// Enum IL for value: IL
        /// </summary>
        [EnumMember(Value = "IL")]
        IL = 19,

        /// <summary>
        /// Enum IN for value: IN
        /// </summary>
        [EnumMember(Value = "IN")]
        IN = 20,

        /// <summary>
        /// Enum IA for value: IA
        /// </summary>
        [EnumMember(Value = "IA")]
        IA = 21,

        /// <summary>
        /// Enum KS for value: KS
        /// </summary>
        [EnumMember(Value = "KS")]
        KS = 22,

        /// <summary>
        /// Enum KY for value: KY
        /// </summary>
        [EnumMember(Value = "KY")]
        KY = 23,

        /// <summary>
        /// Enum LA for value: LA
        /// </summary>
        [EnumMember(Value = "LA")]
        LA = 24,

        /// <summary>
        /// Enum ME for value: ME
        /// </summary>
        [EnumMember(Value = "ME")]
        ME = 25,

        /// <summary>
        /// Enum MD for value: MD
        /// </summary>
        [EnumMember(Value = "MD")]
        MD = 26,

        /// <summary>
        /// Enum MA for value: MA
        /// </summary>
        [EnumMember(Value = "MA")]
        MA = 27,

        /// <summary>
        /// Enum MI for value: MI
        /// </summary>
        [EnumMember(Value = "MI")]
        MI = 28,

        /// <summary>
        /// Enum MN for value: MN
        /// </summary>
        [EnumMember(Value = "MN")]
        MN = 29,

        /// <summary>
        /// Enum MS for value: MS
        /// </summary>
        [EnumMember(Value = "MS")]
        MS = 30,

        /// <summary>
        /// Enum MO for value: MO
        /// </summary>
        [EnumMember(Value = "MO")]
        MO = 31,

        /// <summary>
        /// Enum MT for value: MT
        /// </summary>
        [EnumMember(Value = "MT")]
        MT = 32,

        /// <summary>
        /// Enum NE for value: NE
        /// </summary>
        [EnumMember(Value = "NE")]
        NE = 33,

        /// <summary>
        /// Enum NV for value: NV
        /// </summary>
        [EnumMember(Value = "NV")]
        NV = 34,

        /// <summary>
        /// Enum NH for value: NH
        /// </summary>
        [EnumMember(Value = "NH")]
        NH = 35,

        /// <summary>
        /// Enum NJ for value: NJ
        /// </summary>
        [EnumMember(Value = "NJ")]
        NJ = 36,

        /// <summary>
        /// Enum NM for value: NM
        /// </summary>
        [EnumMember(Value = "NM")]
        NM = 37,

        /// <summary>
        /// Enum NY for value: NY
        /// </summary>
        [EnumMember(Value = "NY")]
        NY = 38,

        /// <summary>
        /// Enum NC for value: NC
        /// </summary>
        [EnumMember(Value = "NC")]
        NC = 39,

        /// <summary>
        /// Enum ND for value: ND
        /// </summary>
        [EnumMember(Value = "ND")]
        ND = 40,

        /// <summary>
        /// Enum MP for value: MP
        /// </summary>
        [EnumMember(Value = "MP")]
        MP = 41,

        /// <summary>
        /// Enum OH for value: OH
        /// </summary>
        [EnumMember(Value = "OH")]
        OH = 42,

        /// <summary>
        /// Enum OK for value: OK
        /// </summary>
        [EnumMember(Value = "OK")]
        OK = 43,

        /// <summary>
        /// Enum OR for value: OR
        /// </summary>
        [EnumMember(Value = "OR")]
        OR = 44,

        /// <summary>
        /// Enum PA for value: PA
        /// </summary>
        [EnumMember(Value = "PA")]
        PA = 45,

        /// <summary>
        /// Enum PR for value: PR
        /// </summary>
        [EnumMember(Value = "PR")]
        PR = 46,

        /// <summary>
        /// Enum RI for value: RI
        /// </summary>
        [EnumMember(Value = "RI")]
        RI = 47,

        /// <summary>
        /// Enum SC for value: SC
        /// </summary>
        [EnumMember(Value = "SC")]
        SC = 48,

        /// <summary>
        /// Enum SD for value: SD
        /// </summary>
        [EnumMember(Value = "SD")]
        SD = 49,

        /// <summary>
        /// Enum TN for value: TN
        /// </summary>
        [EnumMember(Value = "TN")]
        TN = 50,

        /// <summary>
        /// Enum TX for value: TX
        /// </summary>
        [EnumMember(Value = "TX")]
        TX = 51,

        /// <summary>
        /// Enum UT for value: UT
        /// </summary>
        [EnumMember(Value = "UT")]
        UT = 52,

        /// <summary>
        /// Enum VT for value: VT
        /// </summary>
        [EnumMember(Value = "VT")]
        VT = 53,

        /// <summary>
        /// Enum VI for value: VI
        /// </summary>
        [EnumMember(Value = "VI")]
        VI = 54,

        /// <summary>
        /// Enum VA for value: VA
        /// </summary>
        [EnumMember(Value = "VA")]
        VA = 55,

        /// <summary>
        /// Enum WA for value: WA
        /// </summary>
        [EnumMember(Value = "WA")]
        WA = 56,

        /// <summary>
        /// Enum WV for value: WV
        /// </summary>
        [EnumMember(Value = "WV")]
        WV = 57,

        /// <summary>
        /// Enum WI for value: WI
        /// </summary>
        [EnumMember(Value = "WI")]
        WI = 58,

        /// <summary>
        /// Enum WY for value: WY
        /// </summary>
        [EnumMember(Value = "WY")]
        WY = 59

    }

}
