/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountingAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountingAttachmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountingAttachment
        //private AccountingAttachment instance;

        public AccountingAttachmentTests()
        {
            // TODO uncomment below to create an instance of AccountingAttachment
            //instance = new AccountingAttachment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountingAttachment
        /// </summary>
        [Fact]
        public void AccountingAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountingAttachment
            //Assert.IsType<AccountingAttachment>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'FileUrl'
        /// </summary>
        [Fact]
        public void FileUrlTest()
        {
            // TODO unit test for the property 'FileUrl'
        }

    }

}
