/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contact
        //private Contact instance;

        public ContactTests()
        {
            // TODO uncomment below to create an instance of Contact
            //instance = new Contact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contact
        /// </summary>
        [Fact]
        public void ContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contact
            //Assert.IsType<Contact>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsSupplier'
        /// </summary>
        [Fact]
        public void IsSupplierTest()
        {
            // TODO unit test for the property 'IsSupplier'
        }
        /// <summary>
        /// Test the property 'IsCustomer'
        /// </summary>
        [Fact]
        public void IsCustomerTest()
        {
            // TODO unit test for the property 'IsCustomer'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'TaxNumber'
        /// </summary>
        [Fact]
        public void TaxNumberTest()
        {
            // TODO unit test for the property 'TaxNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'RemoteUpdatedAt'
        /// </summary>
        [Fact]
        public void RemoteUpdatedAtTest()
        {
            // TODO unit test for the property 'RemoteUpdatedAt'
        }
        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }

    }

}
