/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreditNoteLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditNoteLineItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditNoteLineItem
        //private CreditNoteLineItem instance;

        public CreditNoteLineItemTests()
        {
            // TODO uncomment below to create an instance of CreditNoteLineItem
            //instance = new CreditNoteLineItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditNoteLineItem
        /// </summary>
        [Fact]
        public void CreditNoteLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditNoteLineItem
            //Assert.IsType<CreditNoteLineItem>(instance);
        }


        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Fact]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }
        /// <summary>
        /// Test the property 'TotalLineAmount'
        /// </summary>
        [Fact]
        public void TotalLineAmountTest()
        {
            // TODO unit test for the property 'TotalLineAmount'
        }
        /// <summary>
        /// Test the property 'TrackingCategory'
        /// </summary>
        [Fact]
        public void TrackingCategoryTest()
        {
            // TODO unit test for the property 'TrackingCategory'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }

    }

}
