/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing ExpenseLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExpenseLineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExpenseLine
        //private ExpenseLine instance;

        public ExpenseLineTests()
        {
            // TODO uncomment below to create an instance of ExpenseLine
            //instance = new ExpenseLine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExpenseLine
        /// </summary>
        [Fact]
        public void ExpenseLineInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExpenseLine
            //Assert.IsType<ExpenseLine>(instance);
        }


        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'NetAmount'
        /// </summary>
        [Fact]
        public void NetAmountTest()
        {
            // TODO unit test for the property 'NetAmount'
        }
        /// <summary>
        /// Test the property 'TrackingCategory'
        /// </summary>
        [Fact]
        public void TrackingCategoryTest()
        {
            // TODO unit test for the property 'TrackingCategory'
        }

    }

}
