/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceLineItemRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceLineItemRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceLineItemRequest
        //private InvoiceLineItemRequest instance;

        public InvoiceLineItemRequestTests()
        {
            // TODO uncomment below to create an instance of InvoiceLineItemRequest
            //instance = new InvoiceLineItemRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceLineItemRequest
        /// </summary>
        [Fact]
        public void InvoiceLineItemRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceLineItemRequest
            //Assert.IsType<InvoiceLineItemRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'TrackingCategory'
        /// </summary>
        [Fact]
        public void TrackingCategoryTest()
        {
            // TODO unit test for the property 'TrackingCategory'
        }

    }

}
