/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceTypeEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceTypeEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceTypeEnum
        //private InvoiceTypeEnum instance;

        public InvoiceTypeEnumTests()
        {
            // TODO uncomment below to create an instance of InvoiceTypeEnum
            //instance = new InvoiceTypeEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceTypeEnum
        /// </summary>
        [Fact]
        public void InvoiceTypeEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceTypeEnum
            //Assert.IsType<InvoiceTypeEnum>(instance);
        }



    }

}
