/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseOrderEndpointRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseOrderEndpointRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseOrderEndpointRequest
        //private PurchaseOrderEndpointRequest instance;

        public PurchaseOrderEndpointRequestTests()
        {
            // TODO uncomment below to create an instance of PurchaseOrderEndpointRequest
            //instance = new PurchaseOrderEndpointRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseOrderEndpointRequest
        /// </summary>
        [Fact]
        public void PurchaseOrderEndpointRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseOrderEndpointRequest
            //Assert.IsType<PurchaseOrderEndpointRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
