/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseOrderStatusEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseOrderStatusEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseOrderStatusEnum
        //private PurchaseOrderStatusEnum instance;

        public PurchaseOrderStatusEnumTests()
        {
            // TODO uncomment below to create an instance of PurchaseOrderStatusEnum
            //instance = new PurchaseOrderStatusEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseOrderStatusEnum
        /// </summary>
        [Fact]
        public void PurchaseOrderStatusEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseOrderStatusEnum
            //Assert.IsType<PurchaseOrderStatusEnum>(instance);
        }



    }

}
