/*
 * Merge Accounting API
 *
 * The unified API for building rich integrations with multiple Accounting & Finance platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.AccountingClient.Api;
using Merge.AccountingClient.Model;
using Merge.AccountingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.AccountingClient.Test.Model
{
    /// <summary>
    ///  Class for testing Status7d1Enum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Status7d1EnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Status7d1Enum
        //private Status7d1Enum instance;

        public Status7d1EnumTests()
        {
            // TODO uncomment below to create an instance of Status7d1Enum
            //instance = new Status7d1Enum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Status7d1Enum
        /// </summary>
        [Fact]
        public void Status7d1EnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" Status7d1Enum
            //Assert.IsType<Status7d1Enum>(instance);
        }



    }

}
